BulkyBookWeb/BulkyBook/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook1.DataAccess.Repository.IRepository;
using BulkyBook1.Models;
using BulkyBook1.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;

        public CompanyController(IUnitOfWork db, IWebHostEnvironment hostEnvironment)
        {
            _UnitOfWork = db;
        }

        public IActionResult Index()
        {
            //IEnumerable<Product> objProductList = _UnitOfWork.Product.GetAll();
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Company company = new();
            if (id == null || id == 0)
            {
                return View(company);
            }
            else
            {
                company = _UnitOfWork.Company.GetFirstOrDefault(u=>u.Id==id);
                return View(company);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (ModelState.IsValid)
            {
                if(obj.Id == 0)
                {
                    _UnitOfWork.Company.Add(obj);
                    TempData["success"] = "Company is created successfuly";
                }
                else
                {
                    _UnitOfWork.Company.Update(obj);
                    TempData["success"] = "Company is updated successfuly";
                }
                
                _UnitOfWork.Save();
                
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _UnitOfWork.Company.GetAll();
            return Json(new { data = companyList });
        }
        [HttpDelete]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _UnitOfWork.Company.GetFirstOrDefault(x => x.Id==id);
            if (obj == null)
                return Json(new { success = false, message = "Error while deleting" });
            _UnitOfWork.Company.Remove(obj);
            _UnitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion API CALLS
    }
}

BulkyBookWeb/BulkyBook/Areas/Admin/Views/Company/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Company List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Company
            </a>
        </div>
    </div>
    <br />
<table id="tblData" class="table table-bordered table-striped" style="width:100%;">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Phone Number</th>
            <th></th>
        </tr>
    </thead>
</table>
</div>
@section Scripts{
    <script src="~/js/company.js"></script>
}

BulkyBookWeb/BulkyBook/Areas/Admin/Views/Company/Upsert.cshtml
@model Company
<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <div class="row">
        <div class="col-10">
                </div>
    <div class="border p-3 m-4 row">
        <div class="col-12 pb-2">
            <h2 class="text-primary">@(Model.Id!=0?"Update":"Create") Company</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <input asp-for="Id" hidden />
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StreetAddress"></label>
            <input asp-for="StreetAddress" class="form-control"/>
            <span asp-validation-for="StreetAddress" class="text-danger"></span>
        </div>
        <div class="mb-3 col-6">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
                <div class="mb-3 col-6">
            <label asp-for="State"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
                <div class="mb-3 col-6">
            <label asp-for="PostalCode"></label>
            <input asp-for="PostalCode" class="form-control" />
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>
        <div class="mb-3 col-6">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="col-12">
            @if(Model.Id!=0)
            {
                <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
            }
            else
            {
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            }
            
        <a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
        </div>
    </div>
 </div>

</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}