FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/CategoryController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Repository;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Contributor")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var categoryList = _unitOfWork.Category.GetAll();

            return View(categoryList);
        }

        //Create
        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View();
        }

        //Update
        //Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)      
                return NotFound();

            var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == id);

            if (categoryFromDb == null)
                return NotFound();

            return View(categoryFromDb);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Category obj)
        {
            if (ModelState.IsValid)
            {
                
                _unitOfWork.Category.Update(obj);

                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [Authorize(Roles = SD.Role_Blog_Owner)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id);
            _unitOfWork.Post.Delete(post);

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Repository;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Contributor")]
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        IEnumerable<Post> postList;
        public PostController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IList<PostVM> postVMs = new List<PostVM>();

            postList = _unitOfWork.Post.GetAll();
            foreach (var post in postList)
            {
                postVMs.Add(new PostVM()
                {
                    Post = post,
                    TimeSpan = Helper.TimeCompare(post.PostedOn)
                });
            }


            return View(postVMs);
        }

        //Create
        //Get
        public IActionResult Create()
        {
            PostVM postVM = new()
            {
                Post = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TagList = _unitOfWork.Tag.GetAll().ToList()

            };
            
            return View(postVM);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PostVM obj)
        {
            if (ModelState.IsValid)
            {
                //Set Total Rate
                obj.Post.TotalRate = 5;

                //Set Published
                obj.Post.Published = false;
                if (obj.Published == "true")
                    obj.Post.Published = true;
                
                //Set UrlSlug
                var stringArr = obj.Post.Title.Split(' ');
                var urlSlug = new StringBuilder();
                foreach (var i in stringArr)
                {
                    urlSlug.Append("-"+i);
                }
                
                obj.Post.UrlSlug = urlSlug.ToString();

                _unitOfWork.Post.Add(obj.Post);
                _unitOfWork.Save();


                var lastPost = _unitOfWork.Post.GetAll().OrderByDescending(p => p.Id).FirstOrDefault();
                if(lastPost != null)
                {
                    //add new record to PostTagMap table
                    foreach (var tagName in obj.SelectedTag)
                    {
                        var tag = _unitOfWork.Tag.GetFirstOrDefault(t => t.Name == tagName);
                        if (tag != null)
                        {
                            var postTagMap = new PostTagMap()
                            {
                                PostId = lastPost.Id,
                                TagId = tag.Id
                            };

                            _unitOfWork.PostTagMap.Add(postTagMap);

                        }
                    }
                }
                

                //Add new Post
                
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Update
        //Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)      
                return NotFound();

            PostVM postVM = new()
            {
                Post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TagList = _unitOfWork.Tag.GetAll().ToList()

            };

            return View(postVM);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(PostVM obj)
        {
            if (ModelState.IsValid)
            {
                //Set Published
                obj.Post.Published = false;
                if (obj.Published == "true")
                    obj.Post.Published = true;

                //Set Modified 
                obj.Post.Modified = DateTime.Now;

                //update PostTagMap table
            
                List<PostTagMap> postTagMapFomrDb = _unitOfWork.PostTagMap.GetAll(t => t.PostId == obj.Post.Id).ToList();
                //Delete Old PostTagMap
                for (var i = 0; i < postTagMapFomrDb.Count(); i++)
                {
                    _unitOfWork.PostTagMap.Delete(postTagMapFomrDb[i]);
                }
                _unitOfWork.Save();

                //Add new Post Tag Map
                foreach (var tagName in obj.SelectedTag)
                {
                    var tag = _unitOfWork.Tag.GetFirstOrDefault(t => t.Name == tagName);
                    if (tag != null)
                    {
                        var postTagMap = new PostTagMap()
                        {
                            PostId = obj.Post.Id,
                            TagId = tag.Id
                        };

                        _unitOfWork.PostTagMap.Add(postTagMap);

                    }
                }

                //Update Post
                _unitOfWork.Post.Update(obj.Post);

                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [Authorize(Roles = SD.Role_Blog_Owner)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id);
            _unitOfWork.Post.Delete(post);

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FA.JustBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/AdminStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FA.JustBlog.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />

    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Just Blog Admin Area</a>
        <!-- Sidebar Toggle-->
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" asp-area="Admin" asp-controller="Post" asp-action="Index">
                            Post
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                            Category
                        </a>
                        <a class="nav-link" asp-area="Customer" asp-controller="Post" asp-action="Index">
                            Go to Home Page
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS-->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/diq5cs6vgukdr37g0kk4r9ph9dqy2idzw6b0dzbdtv94rr2w/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FA.JustBlog/FA.JustBlog/Areas/Admin/Views/Shared/_PartialEdittor.cshtml
@section Scripts{
    <script>
            tinymce.init({
            selector: '#tiny',
            plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
            toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
            toolbar_mode: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
        });
        function ValidateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Please upload an Image!',
                });
                return false;
            }
            return true;
        }
    </script>
}